### ISSUE TITLE
[FEATURE] Improve design of copy to clipboard

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/ThecyberX#29]
### Detailed description

When we click on the copy icon 

![image](https://user-images.githubusercontent.com/44284877/197326780-b1aae38b-5840-4c7c-821e-d004344bb334.png)

Copied. info is coming at the bottom 

### Context

copied. info should be came at the top-center  or  bottom-center
and only for 2 seconds.

### Possible implementation

Using styled-components only

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Codefreak69** [comment]
can you assign this to me

**Comment by kabir0x23** [comment]
Great, I am assigning this issue to you.

you can read the README.md file for setup
