### ISSUE TITLE
[FEATURE] Add social media handles in the footer 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/ThecyberX#8]
### Detailed description

Add social media handle in the footer 

### Context

![image](https://user-images.githubusercontent.com/44284877/196152512-08111e0b-cd14-4eaf-a93c-53c2c2263d83.png)

### Possible implementation

You can get links from the homepage

twitter, website and github links

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrsingh11** [comment]
Hey Do you want me to create a footer component?

**Comment by kabir0x23** [comment]
> ![image](https://user-images.githubusercontent.com/86000208/196165442-45d09b42-c6b4-4ec5-8d83-e6524fbffe83.png)
> 
> Does something like this work?

Yes, 

Footer component is already there.

And we have to add social handles at the right side.

**Comment by kabir0x23** [comment]
> Could you assign this issue to me then?

i just have added a temp readme file, you can give a look

**Comment by kabir0x23** [comment]
> ![Screenshot (140)](https://user-images.githubusercontent.com/86000208/196241280-d800b845-0209-4149-84cd-fa868762d804.png) ![Screenshot (139)](https://user-images.githubusercontent.com/86000208/196241288-bad7d4bd-3069-4c73-ad4f-7848f8b1e973.png)
> 
> Shall I merge it? Or is there something else you need

Awesome, 
one changes:

on widescreen, can you do icons at the center of the display

Thanks, after that you can raise your Pull Request

**Comment by rrsingh11** [comment]
Hey @kabir0x23 , can you please review Pull Request #12  and merge it?
