### ISSUE TITLE
[FEATURE] Add routes to the navbar

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/ThecyberX#9]
### Detailed description

Add routes to the navbar

### Context

add dummy nav-list:
- payloads
- tools
- sec-list

you can leave the page empty

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by code-knayam** [comment]
Hi @kabir0x23 , I would like to work on this. Can you please assign this to me

**Comment by kabir0x23** [comment]
> Hi @kabir0x23 , I would like to work on this. Can you please assign this to me

Yes sure , i am assinging this issue to you
and 
We just have added a temp readme file, you can give a look
